In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,76,3])

array([ 1,  2,  3,  4,  5, 76,  3])

In [8]:
x = np.array([[1,2,3,4],[1,12,3,4],[4,6,87,9],[1,36,7,9]])

In [9]:
x

array([[ 1,  2,  3,  4],
       [ 1, 12,  3,  4],
       [ 4,  6, 87,  9],
       [ 1, 36,  7,  9]])

In [10]:
x[1,1]

12

In [11]:
x[1:3,1:3]

array([[12,  3],
       [ 6, 87]])

In [12]:
x[:3,1:3]

array([[ 2,  3],
       [12,  3],
       [ 6, 87]])

In [13]:
x[:3,1:]

array([[ 2,  3,  4],
       [12,  3,  4],
       [ 6, 87,  9]])

In [14]:
x

array([[ 1,  2,  3,  4],
       [ 1, 12,  3,  4],
       [ 4,  6, 87,  9],
       [ 1, 36,  7,  9]])

In [15]:
x.T

array([[ 1,  1,  4,  1],
       [ 2, 12,  6, 36],
       [ 3,  3, 87,  7],
       [ 4,  4,  9,  9]])

In [16]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [17]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
y = np.array([[1,2,3],[2,5,8],[4,2,6]])

In [21]:
y

array([[1, 2, 3],
       [2, 5, 8],
       [4, 2, 6]])

In [19]:
x + y

array([[11, 22, 33],
       [42, 55, 68],
       [74, 82, 96]])

In [22]:
x - y

array([[ 9, 18, 27],
       [38, 45, 52],
       [66, 78, 84]])

In [23]:
x == y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [24]:
x * y

array([[ 10,  40,  90],
       [ 80, 250, 480],
       [280, 160, 540]])

In [25]:
x / y

array([[10. , 10. , 10. ],
       [20. , 10. ,  7.5],
       [17.5, 40. , 15. ]])

In [26]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.random.random((3,4))

array([[0.70603561, 0.2910099 , 0.43291081, 0.43745482],
       [0.64917971, 0.64069227, 0.47930718, 0.91778557],
       [0.21681398, 0.12681751, 0.25044952, 0.21447865]])

In [32]:
np.empty_like(x)

array([[4621819117588971520, 4621819117588971520, 4621819117588971520],
       [4626322717216342016, 4621819117588971520, 4620130267728707584],
       [4625619029774565376, 4630826316843712512, 4624633867356078080]])

In [35]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
x>5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
x[x>5]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
np.sum(x, axis=1)

array([ 60, 150, 240])

In [39]:
np.sum(x,axis=0)

array([120, 150, 180])

In [43]:
np.ones((3,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)